BudjetProject/BudjetProject/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView

from budjetapp import views
from BudjetProject import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('login_signup/',views.login_signup,name='login_signup'),
    path('signup/',views.signup,name='signup'),
    path('experts/',views.experts,name='experts'),
    path('user_dashboard/',views.user_dashboard,name='user_dashboard'),
    path('my_slots/',views.my_slots,name='my_slots'),
    path('book_slot/<int:pk>',views.book_slot,name='book_slot'),

#path('graph/', views.Graph.as_view(), name='graph'),
path('graphs/',views.graphs,name='graph'),
    path('about/',views.about,name='about'),
    path('conults/',views.conults,name='conults'),
    path('cancel_slot/<int:pk>',views.cancel_slot,name='cancel_slot'),
    path('logout/',views.logouttt,name='logout'),
    path('expert_consultants/',views.expert_consultants,name='expert_consultants'),
    path('cons_expert/',views.cons_expert,name='cons_expert')
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BudjetProject/budjetapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class Userdetails(models.Model):
    auth_user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    mobile=models.CharField(max_length=10,null=True)
    image=models.FileField(null=True,upload_to='media/')
    address=models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.auth_user


class Expert(models.Model):

    name=models.CharField(max_length=50,null=True)
    exp_image=models.FileField(null=True,upload_to='experts/')
    description=models.CharField(max_length=1000,null=True)

    def __str__(self):
        return self.name

class Consults(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    exp_image = models.FileField(null=True, upload_to='experts/')
    status=models.CharField(max_length=20,null=True)
    date=models.DateField(auto_now_add=True)
    time=models.TimeField(auto_now_add=True)

    def __str__(self):

        return self.name



class Slots(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    status = models.CharField(max_length=20, null=True)
    date=models.DateField(auto_now_add=True)
    time=models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Graphs(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    status=models.CharField(max_length=60,null=True)
    value=models.CharField(auto_created=True,max_length=30)

    def __str__(self):

        return self.status

BudjetProject/budjetapp/forms.py
from django import forms

from .models import *

class ConsultForm(forms.ModelForm):
    class Meta:
        model=Consults
        fields="__all__"

BudjetProject/budjetapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from .models import *
from django.contrib.auth import authenticate,logout,login
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required(login_url='login_signup')
def index(request):

    return render(request,'index.html',{'experts':Expert.objects.all()})


def login_signup(request):
    error=False
    if request.method=='POST':
        usr=request.POST['user']
        pwd=request.POST['pwd']
        usr=authenticate(username=usr,password=pwd)
        if usr:
            login(request,usr)
            return redirect('home')
        else:
            error=True


    return render(request,'login_signup.html',{'error':error})


def signup(request):
    error = False
    if request.method == 'POST':
        usr = request.POST['user']
        pwd = request.POST['pwd']
        mob = request.POST['mob']
        img = request.FILES['img']
        add = request.POST['add']
        email = request.POST['email']
        usrdata=User.objects.filter(username=usr)
        if not usrdata:
            user=User.objects.create_user(username=usr,password=pwd,email=email)
            Userdetails.objects.create(auth_user=user,mobile=mob,image=img,address=add)
            return redirect('login_signup')
        else:
            error=True

    return render(request,'signup.html',{'error':error})


def logouttt(request):
    logout(request)
    return redirect('home')

@login_required(login_url='login_signup')
def about(request):
    return render(request,'about.html')

@login_required(login_url='login_signup')
def experts(request):
    return render(request,'experts.html')

@login_required(login_url='login_signup')
def user_dashboard(request):
    mde= Userdetails.objects.filter(auth_user=request.user)
    return render(request,'user_dashboard.html',{'profile':mde})

@login_required(login_url='login_signup')
def expert_consultants(request):

    return render(request,'expert_consultants.html',{'experts':Expert.objects.all()})

@login_required(login_url='login_signup')
def cons_expert(request):
    if request.method == 'POST':
       name=request.POST['name']
       img=request.POST['img']
       Consults.objects.create(user=request.user,name=name,status='pending',exp_image=img)
       return render(request, 'expert_consultants.html',{'message':'Ok Your Request For Consult The Expert " '+ name + ' " is added ,We Will Notify You Once Expert Accept Your Request For Consult '})

@login_required(login_url='login_signup')
def conults(request):
    con=Consults.objects.filter(user=request.user)
    return render(request,'conults.html',{'consults':con})

@login_required(login_url='login_signup')
def cancel_slot(request,pk):
    id=Consults.objects.get(id=pk)
    print('expert id =',id)
    satus= id.status


    print('Status  is =',satus)

    print('slot name=',id.name )
    Graphs.objects.create(user=request.user, status=satus)

    if id.status == 'Accepted':

        return render(request,'error.html',{'msg':'Sorry Ur Request Is Accepted By The Expert And Unable to Cancel The  Request..With In Shortly We Will Inform  Ur Slot Day And Time'})
    else:



        id.delete()
    return redirect('conults')



@login_required(login_url='login_signup')
def my_slots(request):

    return render(request,'my_slots.html')

@login_required(login_url='login_signup')
def book_slot(request,pk):
    id=Consults.objects.get(id=pk)
    name=id.name
    satus=id.status
    print('id=',id)
    Graphs.objects.create(user=request.user,status=satus)
    if id.status=='Accepted':
        Slots.objects.create(name=name,status=satus,user=request.user)
        slots=Slots.objects.filter(user=request.user)

        Consults.objects.filter(id=pk).delete()
        return render(request,'my_slots.html',{'slots':slots})
    else:
        messge='Sorry Ur Request Is  not Accepted By The Expert  " '+ name +' " And Unable to Book Ur Slot At This Time ..With In Shortly We Will Inform  Ur Slot Day And Time Once The Expert Is Accepted Ur Request'
    return render(request,'error.html',{'message':messge})




# For creating Charts (or) Graphs with Dynamic User

#class Graph(TemplateView):
 #   template_name ='graph.html'
 #   def get_context_data(self, **kwargs,):
 #       context=super().get_context_data(**kwargs)
  #      context["qs"]=Graphs.objects.all()
  #      return context

def graphs(request):
    qs = Graphs.objects.filter(user=request.user)
    return render(request,'graph.html',{'qs':qs})

BudjetProject/templates/anchor tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2 style="font-family: 'French Script MT';font-size: 45px;color: blue">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You earn well but are unable to save. You have no idea where your salary goes. You are sometimes forced to borrow to pay your bills. If any of these statements applies to you, it’s time to write down a household budget.
Many people are put off by the word budget because they associate it with restrictions on spending and frugal lifestyles. That’s a misconception. Budgeting does not make you spend less, but allows you to spend smart. “A good budget lets you focus your money on the things that are most important to you,” says personal finance expert Carl Richards. By preventing you from overspending on less important items, a budget channelises resources to areas that should be given priority.
</h2>
the concept is anchor tags
external links
sundar pichay
sundar ramachandra pichai:-
sundar pichai(born June 10, 1972[5]), also known as Sundar Pichai (/ˈsʊndɑːr pɪˈtʃaɪ/), is an Indian American business executive.[6] He is an engineer and the chief executive officer (CEO) of Google LLC.[7][8][9] Formerly the Product Chief of Google, Pichai's current rolewas announced on August 10, 2015, as part of the restructuring process that made Alphabet Inc. into Google's parent company,[10] and he assumed the position on October 2, 2015.[11].pichai's facebook account

internal links

</body>
</html>

BudjetProject/templates/budjet.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title> My Home-Budjet</title>
  </head>
  <body>

<br>
<div align="center">
    {% include 'navs.html' %}
</div>



    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

BudjetProject/templates/conults.html
<div align="center">
    {% extends 'user_dashboard.html' %}
    {% block content %}
        <div align="center">
            <h2> All The Experts You Request for Consult</h2>
        <pre>



        </pre>
        <table align="center" border="0">
        <tr>
            <th style="padding-left: 10%">
             Expert<br><br><br>
            </th>
              <th style="padding-left: 20%">
              Name<br><br><br>
            </th>

              <th style="padding-left: 20%">
               Date<br><br><br>
            </th>

              <th style="padding-left: 20%">
               Time<br><br><br>
            </th>

              <th style="padding-left: 20%">
             Status<br><br><br>
            </th>


        </tr>
        {% for consult in consults %}
            <tr>

                <th>
                    <img src="{{ consult.exp_image.url }}" width="200" height="150" style="border-radius: 9.01cm"><br><br><br>
                </th>
                       <th style="padding-left: 20%">
                        {{ consult.name }}<br><br><br>
                       </th>
                        <th style="padding-left: 20%">
                            {{ consult.date }}<br><br><br>
                       </th> <th style="padding-left: 20%">
                         {{ consult.time }} <br> <br>   <br>
                       </th> <th style="padding-left: 20%;color: greenyellow">
                             <h4>{{ consult.status }}</h4><br><br><br>
                       </th>
              </th> <th style="padding-left: 30%;color: greenyellow">
                <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <form action="{% url 'cancel_slot' consult.id %}" method="post" >{% csrf_token %}<button type="submit" class="btn btn-outline-warning" style="border-radius: 0.9cm" > CancelSlot</button></form>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <form action="{% url 'book_slot' consult.id %}" method="post" >{% csrf_token %}<button type="submit" class="btn btn-outline-warning" style="border-radius: 0.9cm" > BookSlot</button></form></h4><br><br><br>
                       </th>


            </tr>
              {% endfor %}
        </table>







        </div>
    {% endblock %}
</div>

BudjetProject/templates/error.html
{% extends 'user_dashboard.html' %}

{% block content %}<br><br><br><br><br><br>
    <div align="center">
    {% if msg %}
        <h3>{{ msg }}</h3>
    {% endif %}
     {% if message %}
        <h3>{{ message }}</h3>
    {% endif %}
</div>
{% endblock %}

BudjetProject/templates/graph.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title></title>
          <script>
    $(document).ready(function () {
        var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: [{% for i in qs %}'{{ i.status }}',{% endfor %}],
        datasets: [{
            label: 'My Graphs',
            data: [{% for i in qs %}{{ i.value }},{% endfor %} ],
            backgroundColor: [
                'rgb(63, 191, 63)',
                'rgb(240, 29, 78)',
                'rgba(221, 248, 11, 0.9)',
                'rgb(75, 192, 192, 0.2)',
                'rgb(153, 102, 255, 0.2)',

            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',

            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
    });
    </script>
  </head>
  <body>

  <div align="center">
      {% include 'navs.html' %}
  </div>
  <br><br>
  <div align="center" style="padding-left: 15%;padding-right: 15%;">
<nav class="navbar navbar-expand-lg navbar-light bg-dark" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'user_dashboard' %}"><span style="color: white" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Profile</span> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
      </li>


                 <li class="nav-item">
        <a class="nav-link" href="{% url 'conults' %}" tabindex="-1" ><span style="color: white"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Consultants</span></a>
      </li>



       <li class="nav-item">
        <a class="nav-link" href="{% url 'graph' %}" tabindex="-1" ><span style="color: white" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My Graphs</span></a>
      </li>



    </ul>

  </div>


 {% if request.user.is_authenticated %}
      <div class="cart">
          <a href="{% url 'my_slots' %}" ><button id="cartOpen" class="btn btn-outline-warning" style="border-radius: 0.8cm " ><i class="ti-bag">My Slots = {{ request.user.slots_set.count }}</i><span class="d-xs-none"> </span></button></a>
      </div>
      {% endif %}
</nav>
  </div>
<br><br>
  <div align="center">
      <b style="color: #b70c90
;font-size: 50px">{{ request.user.username }}</b> &nbsp;&nbsp;&nbsp; <i style="font-size: 30px;color: #49c5ff" >Graphical dashboard</i>
  </div> <br><br>


    <canvas id="myChart" width="400" height="100"></canvas>

  </body>
</html>

BudjetProject/templates/lists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

BudjetProject/templates/my_slots.html
{% extends 'user_dashboard.html' %}

{% block content %}<br><br><br><br><br><br>
    <div align="center">
    My Slots<br><br><br>
    {% for i in request.user.slots_set.all %}
        {% if i.status == 'Accepted' %}
        {{ i.date }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ i.time }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ i.name }}<br><br>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

BudjetProject/templates/user_dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %}My Home Budjet/User dashboard {% endblock title %}</title>
  </head>
  <body  >

  <br><br>
  <div align="center">
      {% include 'navs.html' %}
  </div>
  <br><br>
  <div align="center" style="padding-left: 15%;padding-right: 15%;">
<nav class="navbar navbar-expand-lg navbar-light bg-dark" >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'user_dashboard' %}"><span style="color: white" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Profile</span> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
      </li>


                 <li class="nav-item">
        <a class="nav-link" href="{% url 'conults' %}" tabindex="-1" ><span style="color: white"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Consultants</span></a>
      </li>



       <li class="nav-item">
        <a class="nav-link" href="{% url 'graph' %}" tabindex="-1" ><span style="color: white" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My Graphs</span></a>
      </li>



    </ul>

  </div>


 {% if request.user.is_authenticated %}
      <div class="cart">
          <a href="{% url 'my_slots' %}" ><button id="cartOpen" class="btn btn-outline-warning" style="border-radius: 0.8cm " ><i class="ti-bag">My Slots = {{ request.user.slots_set.count }}</i><span class="d-xs-none"> </span></button></a>
      </div>
      {% endif %}
</nav>
  </div>
<br><br>
  {% block  content %}
<h3 align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Profile</h3><br><br>
    {% for i in profile %}
<table align="center">
    <tr>
    <th>
        <img src={{ i.image.url }} width="200"  style="border-radius: 6.0cm " height="200" >
    </th>
        <th>
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ i.auth_user.username }}
            <table align="center">
                <tr>
                    <th>
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ i.auth_user.email }}
                        <table align="center">
                            <tr>
                                  <th>
                         {{ i.mobile }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </th>
                                <tr>                      <th>
                         {{ i.address }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </th></tr>


                        </table>
                    </th>


                </tr>
            </table>
        </th>
</tr></table>
        {% endfor %}
  {% endblock %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>